### ISSUE TITLE
Freezing Window/High CPU Usage

### ISSUE THREAD

**Issue by maxohios** [KalebKE/ME7Tuner#1]
Hello,

When using the program and switching tab, the program will not open the selected tab. Also the CPU usage keeps staying high without any user inputs.

This problem is only in v0.2, Windows 10 pro x64

![afbeelding](https://user-images.githubusercontent.com/31628152/100803655-d105fa00-342b-11eb-9501-9d9d1ff0a658.png)

**Comment by maxohios** [comment]
Here is one error when debugging:

Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "1,000"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at ui.map.map.MapTable$DecimalFormatRenderer.getTableCellRendererComponent(MapTable.java:227)
	at javax.swing.JTable.prepareRenderer(Unknown Source)

**Comment by maxohios** [comment]
Fixed by changing
private final DecimalFormat decimalFormat = new DecimalFormat("#,####"); replaced . by ,
private final DecimalFormat formatter = new DecimalFormat("#,00"); replaced . by ,

**Comment by KalebKE** [comment]
@maxohios 

It seems that the 3D charts backed by the Jzy3d lib aren't exactly performant. The JTabbedPane eagerly loads everything and those 3D are just sitting in the background chewing up CPU cycles. I am not sure about a solution at the moment. I'll have to think about it.
