### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by DwDckQo** [KalebKE/ME7Tuner#8]
Hi i have Java version 16.0.2 i run your program with java -jar ME7Tuner_v0.3.jar. Got this error:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
        at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:171)
        at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
        at com.jogamp.nativewindow.awt.AWTGraphicsConfiguration.create(AWTGraphicsConfiguration.java:125)
        at com.jogamp.newt.awt.NewtCanvasAWT.addNotify(NewtCanvasAWT.java:590)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/java.awt.Panel.addNotify(Panel.java:87)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
        at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729)
        at java.desktop/java.awt.Container.addNotify(Container.java:2801)
        at java.desktop/java.awt.Window.addNotify(Window.java:787)
        at java.desktop/java.awt.Frame.addNotify(Frame.java:493)
        at java.desktop/java.awt.Window.show(Window.java:1049)
        at java.desktop/java.awt.Component.show(Component.java:1720)
        at java.desktop/java.awt.Component.setVisible(Component.java:1667)
        at java.desktop/java.awt.Window.setVisible(Window.java:1032)
        at ui.view.MainManager.start(MainManager.java:32)
        at Main.main(Main.java:6)
        
        Any suggestion ?

**Comment by KalebKE** [comment]
Hi, 
 
The best solution is to run with Java 8.

JZY3D, which draws the graphs, didn't support Java 11+ until March and it has breaking API changes that I haven't had a chance to update.
